TextExpression : concat( "Failed to forward an inbound functional acknowledgment to a backend application. ", "Message ID: ", b2b-message-reference, ", because of the error: ", errorCode, " ", reason, ", Details: ", details)
XpathExpression : concat("Failed to forward an inbound functional acknowledgment to a backend application. ", "Message ID: ", $Current-B2B-File/nsmpr11:B2BFile/nsmpr11:b2b-message-reference , ", because of the error: ", $Forward-Functional-AckFaultObject/nsmpr5:fault/nsmpr5:errorCode , " ",  $Forward-Functional-AckFaultObject/nsmpr5:fault/nsmpr5:reason , ", Details: ",  $Forward-Functional-AckFaultObject/nsmpr5:fault/nsmpr5:details)
NamespaceList : nsmpr11=http://xmlns.oracle.com/cloud/adapter/ftp/Download_One_File/types nsmpr5=http://www.oracle.com/2014/03/ics/fault
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Log-Failed-to-Forward-Func-Ack
VariableDescription : 
VariableType : 
VariableTypeNamespace :