TextExpression : B2BFile
XpathExpression : $Download-One-File/nsmpr3:DownloadFileToICSResponse/nsmpr7:DownloadResponse/nsmpr7:B2BFiles/nsmpr7:B2BFile
NamespaceList : nsmpr7=http://xmlns.oracle.com/cloud/adapter/ftp/Download_One_File/types nsmpr3=http://xmlns.oracle.com/cloud/adapter/ftp/Download_One_File_REQUEST/types
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Current-B2B-File
VariableDescription : 
VariableType : 
VariableTypeNamespace :