TextExpression : "true"
XpathExpression : 'true'
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : isSuccess
VariableDescription : 
VariableType : string
VariableTypeNamespace : http://www.w3.org/2001/XMLSchema