TextExpression : concat( "Failed to translate inbound EDI for file: ", filename, " for trading partner:", msg-group/@trading-partner)
XpathExpression : concat("Failed to translate inbound EDI for file: ", $CurrentFile/nsmpr1:File/nsmpr1:filename   , " for trading partner:", $Current-Message-Group/nsmpr7:msg-group/@trading-partner)
NamespaceList : nsmpr7=http://xmlns.oracle.com/b2b/edi/generic/inbound_translate_response nsmpr1=http://xmlns.oracle.com/cloud/list/pull
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Log-Error2
VariableDescription : 
VariableType : 
VariableTypeNamespace :