TextExpression : msg-group/@connectivity-properties-code != ""
XpathExpression : $Current-Message-Group/nsmpr8:msg-group/@connectivity-properties-code != ""
NamespaceList : nsmpr8=http://xmlns.oracle.com/b2b/edi/generic/inbound_translate_response
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : Needs-Forwarding
VariableName : 
VariableDescription : 
VariableType : 
VariableTypeNamespace :