TextExpression : msg-group
XpathExpression : $Translate/nsmpr10:executeResponse/nsmpr7:TranslateOutput/nsmpr7:msg-group
NamespaceList : nsmpr7=http://xmlns.oracle.com/b2b/edi/generic/inbound_translate_response nsmpr10=http://xmlns.oracle.com/cloud/adapter/ediAdapter/Translate_REQUEST/types
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Current-Message-Group
VariableDescription : 
VariableType : 
VariableTypeNamespace :