TextExpression : msg-group/@type = "ERROR"
XpathExpression : $Current-Message-Group/nsmpr7:msg-group/@type = "ERROR"
NamespaceList : nsmpr7=http://xmlns.oracle.com/b2b/edi/generic/inbound_translate_response
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : Translation Failed
VariableName : 
VariableDescription : 
VariableType : 
VariableTypeNamespace :