TextExpression : concat( "Error processing file: ", filename)
XpathExpression : concat("Error processing file: ", $CurrentFile/nsmpr1:File/nsmpr1:filename)
NamespaceList : nsmpr1=http://xmlns.oracle.com/cloud/list/pull
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Log-File-Level-Error
VariableDescription : 
VariableType : 
VariableTypeNamespace :