TextExpression : File
XpathExpression : $List-Files-in-FTP/nsmpr3:ListFileResponse/nsmpr1:ListResponse/nsmpr1:FileList/nsmpr1:File
NamespaceList : nsmpr3=http://xmlns.oracle.com/cloud/adapter/ftp/List_Files_in_FTP_REQUEST/types nsmpr1=http://xmlns.oracle.com/cloud/list/pull
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : CurrentFile
VariableDescription : 
VariableType : 
VariableTypeNamespace :