TextExpression : message
XpathExpression : "keepAlways"
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Delete-Or-Keep-Processed-Files
VariableDescription : "deleteAlways","keepOnError","keepAlways"
VariableType : 
VariableTypeNamespace :