TextExpression : message
XpathExpression : "_backup"
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Move-To-Directory
VariableDescription : Processed files are moved to this directory depending on Delete-Or-Keep-Processed-Files
VariableType : 
VariableTypeNamespace :