TextExpression : message
XpathExpression : "_processed"
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Processed-File-Extension
VariableDescription : If processing is successful, rename file with this extension (e.g. "_processed"), depending on Delete-Or-Keep-Processed-Files
VariableType : 
VariableTypeNamespace :