TextExpression : msg-group/@type = "FA" and msg-group/@direction = "OUTBOUND"
XpathExpression : $Current-Message-Group/nsmpr7:msg-group/@type = "FA" and $Current-Message-Group/nsmpr7:msg-group/@direction = "OUTBOUND"
NamespaceList : nsmpr7=http://xmlns.oracle.com/b2b/edi/generic/inbound_translate_response
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : Outbound-Ack
VariableName : 
VariableDescription : 
VariableType : 
VariableTypeNamespace :