TextExpression : Delete-Or-Keep-Processed-Files = "keepOnError" or Delete-Or-Keep-Processed-Files = "keepAlways"
XpathExpression : $selfProperties/nsmpr3:properties/nsmpr3:Delete-Or-Keep-Processed-Files = "keepOnError" or $selfProperties/nsmpr3:properties/nsmpr3:Delete-Or-Keep-Processed-Files = "keepAlways"
NamespaceList : nsmpr3=http://www.oracle.com/2014/03/ic/integration/properties
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : Keep-File
VariableName : 
VariableDescription : 
VariableType : 
VariableTypeNamespace :